{% set name = "wsgidav" %}
{% set version = "4.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f2055a949f69db3e8c1f37d787f6ffd076ea29d561dda68918289a2a5d41a93

build:
  entry_points:
    - wsgidav = wsgidav.server.server_cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bcrypt >=4.0,<5
    - defusedxml
    - jinja2
    - json5
    - passlib
    - pyyaml

test:
  imports:
    - wsgidav
  commands:
    - pip check
    - wsgidav --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mar10/wsgidav
  summary: Generic and extendable WebDAV server based on WSGI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timj
