{% set name = "wsgidav" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WsgiDAV-{{ version }}.tar.gz
  sha256: 4c3c24ac01b656a9edcb0014f31717ca8b9a3ec7d7cd9adc39d9ce1b00bfe759

build:
  entry_points:
    - wsgidav = wsgidav.server.server_cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - defusedxml
    - jinja2
    - json5
    - pyyaml

test:
  imports:
    - wsgidav
  commands:
    - pip check
    - wsgidav --help
  requires:
    - pip

about:
  home: https://github.com/mar10/wsgidav
  summary: Generic and extendable WebDAV server based on WSGI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timj
