{% set name = "wsgidav" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WsgiDAV-{{ version }}.tar.gz
  sha256: 53b69c8efb94fd06b90db806833555dede2f6a9ce2458d5a29eee03154773840

build:
  entry_points:
    - wsgidav = wsgidav.server.server_cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - defusedxml
    - jinja2
    - json5
    - pyyaml

test:
  imports:
    - wsgidav
  commands:
    - pip check
    - wsgidav --help
  requires:
    - pip

about:
  home: https://github.com/mar10/wsgidav
  summary: Generic and extendable WebDAV server based on WSGI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timj
